import { AssetTileProps } from "@/components/AssetTile";

export const assets: AssetTileProps[] = [
    {
        id: '1',
        title: 'MacBook Pro 14"',
        price: '1,850',
        remarks: '20',
        ratings: 4.9,
        location: 'Accra, Ghana',
        assetImage: '/images/assets/speaker.png',
        numReviews: 124,
        // type: 'individual',
        howOld: 'barely used',
    },
    {
        id: '2',
        title: 'Office Space Rental',
        price: '950/month',
        // remarks: '14',
        ratings: 4.5,
        location: 'East Legon, Accra',
        assetImage: '/images/assets/cactus.png',
        numReviews: 48,
        type: 'business',
        howOld: 'standard',
    },
    {
        id: '3',
        title: 'iPhone 15 Pro',
        price: '1,100',
        remarks: '31',
        ratings: 4.8,
        location: 'Tema, Ghana',
        assetImage: '/images/assets/suit.png',
        numReviews: 89,
        type: 'individual',
        howOld: 'brand new',
    },
    {
        id: '4',
        title: 'Gaming Chair',
        price: '$220',
        remarks: 'Ergonomic chair with lumbar support',
        ratings: 4.1,
        location: 'Kumasi, Ghana',
        assetImage: '/images/assets/chairs.png',
        numReviews: 31,
        type: 'business',
        howOld: 'fairly used',
    },
]