import { AssetTileProps } from "@/components/AssetTile";
import { VendorAssetTileProps } from "@/components/vendor/VendorAssetTile";

export const assets: AssetTileProps[] = [
    {
        title: 'MacBook Pro 14"',
        price: '1,850',
        remarks: '20',
        ratings: 4.9,
        location: 'Accra, Ghana',
        assetImage: '/images/assets/speaker.png',
        numReviews: 124,
        type: 'individual',
        howOld: 'barely used',
    },
    {
        title: 'Office Space Rental',
        price: '950/month',
        remarks: '14',
        ratings: 4.5,
        location: 'East Legon, Accra',
        assetImage: '/images/assets/cactus.png',
        numReviews: 48,
        type: 'business',
        howOld: 'standard',
    },
    {
        title: 'iPhone 15 Pro',
        price: '1,100',
        remarks: '31',
        ratings: 4.8,
        location: 'Tema, Ghana',
        assetImage: '/images/assets/suit.png',
        numReviews: 89,
        type: 'individual',
        howOld: 'brand new',
    },
    {
        title: 'Gaming Chair',
        price: '$220',
        remarks: 'Ergonomic chair with lumbar support',
        ratings: 4.1,
        location: 'Kumasi, Ghana',
        assetImage: '/images/assets/chairs.png',
        numReviews: 31,
        type: 'business',
        howOld: 'fairly used',
    },
]

export const vendorAssets: VendorAssetTileProps[] = [
    {
        title: 'Toyota Corolla 2018',
        price: '13,500',
        remarks: 'Automatic transmission, low mileage',
        ratings: 4.6,
        location: 'Takoradi, Ghana',
        status: 'listed',
        assetImage: '/images/assets/speaker.png',
        numReviews: 57,
        type: 'individual',
        howOld: 'standard',
    },
    {
        title: 'Canon EOS R50',
        price: '780',
        remarks: 'Mirrorless camera with kit lens included',
        ratings: 4.3,
        location: 'Cape Coast, Ghana',
        status: 'paused',
        assetImage: '/images/assets/cactus.png',
        numReviews: 19,
        type: 'business',
        howOld: 'barely used',
    },
    {
        title: 'Wooden Dining Set',
        price: '430',
        status: 'listed',
        remarks: '6-seater handcrafted dining table',
        ratings: 3.9,
        location: 'Madina, Accra',
        assetImage: '/images/assets/chairs.jpg',
        numReviews: 14,
        type: 'individual',
        howOld: 'fairly used',
    },
]