import { AssetTileProps } from "@/components/AssetTile";

export const assets: AssetTileProps[] = [
    {
        title: 'MacBook Pro 14"',
        price: '1,850',
        remarks: '20',
        ratings: 4.9,
        location: 'Accra, Ghana',
        assetImage: '/images/speaker.png',
        numReviews: 124,
        type: 'individual',
        howOld: 'barely used',
    },
    {
        title: 'Office Space Rental',
        price: '950/month',
        remarks: '14',
        ratings: 4.5,
        location: 'East Legon, Accra',
        assetImage: '/images/speaker.png',
        numReviews: 48,
        type: 'business',
        howOld: 'standard',
    },
    {
        title: 'iPhone 15 Pro',
        price: '1,100',
        remarks: '31',
        ratings: 4.8,
        location: 'Tema, Ghana',
        assetImage: '/images/speaker.png',
        numReviews: 89,
        type: 'individual',
        howOld: 'brand new',
    },
    // {
    //     title: 'Gaming Chair',
    //     price: '$220',
    //     remarks: 'Ergonomic chair with lumbar support',
    //     ratings: 4.1,
    //     location: 'Kumasi, Ghana',
    //     assetImage: '/images/gaming-chair.jpg',
    //     numReviews: 31,
    //     type: 'business',
    //     howOld: 'fairly used',
    // },
    // {
    //     title: 'Toyota Corolla 2018',
    //     price: '$13,500',
    //     remarks: 'Automatic transmission, low mileage',
    //     ratings: 4.6,
    //     location: 'Takoradi, Ghana',
    //     assetImage: '/images/corolla.jpg',
    //     numReviews: 57,
    //     type: 'individual',
    //     howOld: 'standard',
    // },
    // {
    //     title: 'Canon EOS R50',
    //     price: '$780',
    //     remarks: 'Mirrorless camera with kit lens included',
    //     ratings: 4.3,
    //     location: 'Cape Coast, Ghana',
    //     assetImage: '/images/canon-r50.jpg',
    //     numReviews: 19,
    //     type: 'business',
    //     howOld: 'barely used',
    // },
    // {
    //     title: 'Wooden Dining Set',
    //     price: '$430',
    //     remarks: '6-seater handcrafted dining table',
    //     ratings: 3.9,
    //     location: 'Madina, Accra',
    //     assetImage: '/images/dining-set.jpg',
    //     numReviews: 14,
    //     type: 'individual',
    //     howOld: 'fairly used',
    // },
    // {
    //     title: 'Samsung 55" Smart TV',
    //     price: '$620',
    //     remarks: '4K UHD with Netflix and YouTube support',
    //     ratings: 4.7,
    //     location: 'Spintex, Accra',
    //     assetImage: '/images/samsung-tv.jpg',
    //     numReviews: 73,
    //     type: 'business',
    //     howOld: 'brand new',
    // },
]
