import { BottomSheetProps } from "@/components/BottomSheet";

export const rentals: BottomSheetProps[] = [
    {
        id: '1',
        uid: 'RT00',
        name: 'Portable JBL Speaker',
        price: '$45/day',
        assetSrc: '/images/assets/speaker.png',
        quantity: '12',
        progress: 90,
        rate: 100,
        about: 'Premier luxury event rentals in Accra. We specialize in high-end marquee tents, authentic Kente-themed decor, and international standard banquet seating for your most prestigious occasions.',
        owner: 'Scylla Kwofie',
        rating: 4.2,
        reviews: 20,
        ownerSrc: '/images/Avatar.png',
        category: 'Electronic',
        description: 'High fidelity portable sound system suitable for indoor and outdoor events.'
    },
    {
        id: '2',
        uid: 'RT00',
        name: 'Bluetooth Party Speaker',
        price: '$60/day',
        assetSrc: '/images/assets/cactus.png',
        quantity: '8',
        progress: 40,
        rate: 120,
        about: 'Trusted rental solutions for parties, weddings, and premium social gatherings across Ghana.',
        owner: 'Daniel Mensah',
        rating: 4.5,
        reviews: 48,
        ownerSrc: '/images/Avatar.png',
        category: 'Decor',
        description: 'Stylish decorative cactus arrangement perfect for modern event aesthetics.'
    },
    {
        id: '3',
        uid: 'RT00',
        name: 'Studio Monitor Speaker',
        price: '$75/day',
        assetSrc: '/images/assets/camcorder.png',
        quantity: '15',
        progress: 55,
        rate: 150,
        about: 'Industry-grade multimedia and event equipment rentals for creators and professionals.',
        owner: 'Ama Serwaa',
        rating: 4.8,
        reviews: 61,
        ownerSrc: '/images/Avatar.png',
        category: 'Media',
        description: 'Professional camcorder equipment with stabilized recording and cinematic quality.'
    },
    {
        id: '4',
        uid: 'RT00',
        name: 'Wireless Bass Speaker',
        price: '$50/day',
        assetSrc: '/images/assets/chairs.png',
        quantity: '20',
        progress: 72,
        rate: 80,
        about: 'Elegant furniture and seating arrangements tailored for luxury experiences.',
        owner: 'Kelvin Arthur',
        rating: 4.1,
        reviews: 16,
        ownerSrc: '/images/Avatar.png',
        category: 'Furniture',
        description: 'Premium outdoor chair set crafted for weddings, conferences, and receptions.'
    },
    {
        id: '5',
        uid: 'RT00',
        name: 'Outdoor PA Speaker',
        price: '$95/day',
        assetSrc: '/images/assets/generator.png',
        quantity: '6',
        progress: 10,
        rate: 200,
        about: 'Reliable power and stage support services for concerts and outdoor productions.',
        owner: 'Michael Owusu',
        rating: 4.7,
        reviews: 72,
        ownerSrc: '/images/Avatar.png',
        category: 'Power',
        description: 'Heavy-duty industrial generator suitable for large-scale outdoor events.'
    },
    {
        id: '6',
        uid: 'RT00',
        name: 'Mini Smart Speaker',
        price: '$30/day',
        assetSrc: '/images/assets/suit.png',
        quantity: '25',
        progress: 38,
        rate: 65,
        about: 'Luxury fashion and formal wear rentals for elite ceremonies and corporate occasions.',
        owner: 'Vanessa Kwarteng',
        rating: 4.3,
        reviews: 29,
        ownerSrc: '/images/Avatar.png',
        category: 'Fashion',
        description: 'Elegant formal suit designed for weddings, galas, and executive appearances.'
    },
]